default: &default
  adapter: postgresql
  encoding: unicode
  max_connections: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV.fetch("DATABASE_URL") { "localhost" } %>
  port: <%= ENV.fetch("DATABASE_PORT") { 5432 } %>
  username: <%= ENV.fetch("DATABASE_USERNAME") { "postgres" } %>
  password: <%= ENV.fetch("DATABASE_PASSWORD") { "password" } %>
  database: <%= ENV.fetch("DATABASE_NAME") { "ror_with_docker" } %>
  sslmode: require

development:
  <<: *default
  database: <%= ENV.fetch("DATABASE_NAME") { "ror_with_docker_development" } %>

test:
  <<: *default
  database: <%= ENV.fetch("DATABASE_NAME") { "ror_with_docker_test" } %>

production:
  <<: *default
  database: <%= ENV.fetch("DATABASE_NAME") { "ror_with_docker_production" } %>
