default: &default
  adapter: postgresql
  encoding: unicode
  max_connections: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV.fetch("DB_HOST") { "localhost" } %>
  port: <%= ENV.fetch("DB_PORT") { 5432 } %>
  username: <%= ENV.fetch("DB_USERNAME") { "postgres" } %>
  password: <%= ENV.fetch("DB_PASSWORD") { "password" } %>

development:
  <<: *default
  database: <%= ENV.fetch("DB_NAME") { "ror_with_docker_development" } %>

test:
  <<: *default
  database: <%= ENV.fetch("DB_NAME") { "ror_with_docker_test" } %>

production:
  <<: *default
  database: <%= ENV.fetch("DB_NAME") { "ror_with_docker_production" } %>
